fragment CoreHeading on CoreHeading {
  attributes {
    align
    anchor
    backgroundColor
    className
    content
    cssClassName
    fontFamily
    fontSize
    gradient
    level
    lock
    metadata
    placeholder
    style
    textAlign
    textColor
  }
}
