#import '~/.queries/fragments/EditorBlock.fragment.gql';

fragment NodeWithEditorBlocks on NodeWithEditorBlocks {
  editorBlocks {
    ...EditorBlock
    innerBlocks {
      ...EditorBlock
    }
  }
}
