#import '~/.queries/fragments/ContentNode.fragment.gql';
#import '~/.queries/fragments/NodeWithFeaturedImage.fragment.gql';
#import '~/.queries/fragments/NodeWithEditorBlocks.fragment.gql';

fragment Page on Page {
  ...ContentNode
  ...NodeWithFeaturedImage
  ...NodeWithEditorBlocks
  content
  isFrontPage
  isPostsPage
  isPreview
  isPrivacyPage
  isRestricted
  isRevision
  title
}
